### ISSUE TITLE
Request to merge / unfork:  Shield-Studies-Addon-Utils

### ISSUE THREAD

**Issue by gregglind** [mozilla/pioneer-utils#25]
I realize this was made fast.  When we catch a little breath, can we merge these two things / ensure that functionality exists in one place?

**Comment by rehandalal** [comment]
Yep, this is on our radar.

**Comment by motin** [comment]
I added an issue to write tests in pioneer-utils: https://github.com/mozilla/pioneer-utils/issues/39
Since we are now requiring tests for everything in utils, I think we should wait with merging the library until there are tests in place, so that we can see that the tests are still passing after the merge.

**Comment by motin** [comment]
Note: It'd be great if you write tests that are portable to utils. The actual test system to be used in utils is yet to be decided, join the discussion here on how to best test pioneer and shield utils: https://github.com/mozilla/shield-studies-addon-utils/issues/125
